// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Coral.MasterData.Persistance.Entities
{
    public partial class EmployeeStatus
    {
        public int StatusId { get; set; }
        public string Description { get; set; }
        public bool? IsDeleted { get; set; }
    }
}